# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MCLStage.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(748, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.PB_L1x = QtGui.QPushButton(Form)
        self.PB_L1x.setGeometry(QtCore.QRect(170, 190, 51, 61))
        self.PB_L1x.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("L1Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_L1x.setIcon(icon)
        self.PB_L1x.setIconSize(QtCore.QSize(50, 50))
        self.PB_L1x.setAutoDefault(False)
        self.PB_L1x.setDefault(False)
        self.PB_L1x.setFlat(False)
        self.PB_L1x.setObjectName(_fromUtf8("PB_L1x"))
        self.PB_L2x = QtGui.QPushButton(Form)
        self.PB_L2x.setGeometry(QtCore.QRect(110, 190, 61, 61))
        self.PB_L2x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_L2x.setAutoFillBackground(False)
        self.PB_L2x.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("L2Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_L2x.setIcon(icon1)
        self.PB_L2x.setIconSize(QtCore.QSize(50, 50))
        self.PB_L2x.setCheckable(False)
        self.PB_L2x.setFlat(False)
        self.PB_L2x.setObjectName(_fromUtf8("PB_L2x"))
        self.PB_L3x = QtGui.QPushButton(Form)
        self.PB_L3x.setGeometry(QtCore.QRect(40, 190, 71, 61))
        self.PB_L3x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_L3x.setAutoFillBackground(False)
        self.PB_L3x.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("L3Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_L3x.setIcon(icon2)
        self.PB_L3x.setIconSize(QtCore.QSize(70, 70))
        self.PB_L3x.setCheckable(False)
        self.PB_L3x.setFlat(False)
        self.PB_L3x.setObjectName(_fromUtf8("PB_L3x"))
        self.PB_R2x = QtGui.QPushButton(Form)
        self.PB_R2x.setGeometry(QtCore.QRect(350, 190, 61, 61))
        self.PB_R2x.setMouseTracking(True)
        self.PB_R2x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_R2x.setAutoFillBackground(False)
        self.PB_R2x.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("R2Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_R2x.setIcon(icon3)
        self.PB_R2x.setIconSize(QtCore.QSize(50, 50))
        self.PB_R2x.setCheckable(False)
        self.PB_R2x.setFlat(False)
        self.PB_R2x.setObjectName(_fromUtf8("PB_R2x"))
        self.PB_R3x = QtGui.QPushButton(Form)
        self.PB_R3x.setGeometry(QtCore.QRect(410, 190, 71, 61))
        self.PB_R3x.setMouseTracking(True)
        self.PB_R3x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_R3x.setAutoFillBackground(False)
        self.PB_R3x.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("R3Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_R3x.setIcon(icon4)
        self.PB_R3x.setIconSize(QtCore.QSize(70, 70))
        self.PB_R3x.setCheckable(False)
        self.PB_R3x.setFlat(False)
        self.PB_R3x.setObjectName(_fromUtf8("PB_R3x"))
        self.PB_R1x = QtGui.QPushButton(Form)
        self.PB_R1x.setGeometry(QtCore.QRect(300, 190, 51, 61))
        self.PB_R1x.setMouseTracking(True)
        self.PB_R1x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_R1x.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("R1Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_R1x.setIcon(icon5)
        self.PB_R1x.setIconSize(QtCore.QSize(50, 50))
        self.PB_R1x.setAutoDefault(False)
        self.PB_R1x.setDefault(False)
        self.PB_R1x.setFlat(False)
        self.PB_R1x.setObjectName(_fromUtf8("PB_R1x"))
        self.PB_U1x = QtGui.QPushButton(Form)
        self.PB_U1x.setGeometry(QtCore.QRect(230, 130, 61, 51))
        self.PB_U1x.setMouseTracking(True)
        self.PB_U1x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_U1x.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("U1Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_U1x.setIcon(icon6)
        self.PB_U1x.setIconSize(QtCore.QSize(50, 50))
        self.PB_U1x.setAutoDefault(False)
        self.PB_U1x.setDefault(False)
        self.PB_U1x.setFlat(False)
        self.PB_U1x.setObjectName(_fromUtf8("PB_U1x"))
        self.PB_R3x_2 = QtGui.QPushButton(Form)
        self.PB_R3x_2.setGeometry(QtCore.QRect(230, 0, 61, 71))
        self.PB_R3x_2.setMouseTracking(True)
        self.PB_R3x_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_R3x_2.setAutoFillBackground(False)
        self.PB_R3x_2.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("U3Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_R3x_2.setIcon(icon7)
        self.PB_R3x_2.setIconSize(QtCore.QSize(70, 70))
        self.PB_R3x_2.setCheckable(False)
        self.PB_R3x_2.setFlat(False)
        self.PB_R3x_2.setObjectName(_fromUtf8("PB_R3x_2"))
        self.PB_R2x_2 = QtGui.QPushButton(Form)
        self.PB_R2x_2.setGeometry(QtCore.QRect(230, 70, 61, 61))
        self.PB_R2x_2.setMouseTracking(True)
        self.PB_R2x_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_R2x_2.setAutoFillBackground(False)
        self.PB_R2x_2.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("U2Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_R2x_2.setIcon(icon8)
        self.PB_R2x_2.setIconSize(QtCore.QSize(50, 50))
        self.PB_R2x_2.setCheckable(False)
        self.PB_R2x_2.setFlat(False)
        self.PB_R2x_2.setObjectName(_fromUtf8("PB_R2x_2"))
        self.PB_D1x = QtGui.QPushButton(Form)
        self.PB_D1x.setGeometry(QtCore.QRect(230, 260, 61, 51))
        self.PB_D1x.setMouseTracking(True)
        self.PB_D1x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_D1x.setAutoFillBackground(False)
        self.PB_D1x.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("D1Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_D1x.setIcon(icon9)
        self.PB_D1x.setIconSize(QtCore.QSize(50, 50))
        self.PB_D1x.setCheckable(False)
        self.PB_D1x.setFlat(False)
        self.PB_D1x.setObjectName(_fromUtf8("PB_D1x"))
        self.PB_D3x = QtGui.QPushButton(Form)
        self.PB_D3x.setGeometry(QtCore.QRect(230, 370, 61, 71))
        self.PB_D3x.setMouseTracking(True)
        self.PB_D3x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_D3x.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("D3Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_D3x.setIcon(icon10)
        self.PB_D3x.setIconSize(QtCore.QSize(70, 70))
        self.PB_D3x.setAutoDefault(False)
        self.PB_D3x.setDefault(False)
        self.PB_D3x.setFlat(False)
        self.PB_D3x.setObjectName(_fromUtf8("PB_D3x"))
        self.PB_D2x = QtGui.QPushButton(Form)
        self.PB_D2x.setGeometry(QtCore.QRect(230, 310, 61, 61))
        self.PB_D2x.setMouseTracking(True)
        self.PB_D2x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_D2x.setAutoFillBackground(False)
        self.PB_D2x.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("D2Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_D2x.setIcon(icon11)
        self.PB_D2x.setIconSize(QtCore.QSize(50, 50))
        self.PB_D2x.setCheckable(False)
        self.PB_D2x.setFlat(False)
        self.PB_D2x.setObjectName(_fromUtf8("PB_D2x"))
        self.PB_ZD3x = QtGui.QPushButton(Form)
        self.PB_ZD3x.setGeometry(QtCore.QRect(550, 370, 61, 71))
        self.PB_ZD3x.setMouseTracking(True)
        self.PB_ZD3x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_ZD3x.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("ZD3Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_ZD3x.setIcon(icon12)
        self.PB_ZD3x.setIconSize(QtCore.QSize(70, 70))
        self.PB_ZD3x.setAutoDefault(False)
        self.PB_ZD3x.setDefault(False)
        self.PB_ZD3x.setFlat(False)
        self.PB_ZD3x.setObjectName(_fromUtf8("PB_ZD3x"))
        self.PB_ZD1x = QtGui.QPushButton(Form)
        self.PB_ZD1x.setGeometry(QtCore.QRect(550, 260, 61, 51))
        self.PB_ZD1x.setMouseTracking(True)
        self.PB_ZD1x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_ZD1x.setAutoFillBackground(False)
        self.PB_ZD1x.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("ZD1Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_ZD1x.setIcon(icon13)
        self.PB_ZD1x.setIconSize(QtCore.QSize(50, 50))
        self.PB_ZD1x.setCheckable(False)
        self.PB_ZD1x.setFlat(False)
        self.PB_ZD1x.setObjectName(_fromUtf8("PB_ZD1x"))
        self.PB_ZD2x = QtGui.QPushButton(Form)
        self.PB_ZD2x.setGeometry(QtCore.QRect(550, 310, 61, 61))
        self.PB_ZD2x.setMouseTracking(True)
        self.PB_ZD2x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_ZD2x.setAutoFillBackground(False)
        self.PB_ZD2x.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("ZD2Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_ZD2x.setIcon(icon14)
        self.PB_ZD2x.setIconSize(QtCore.QSize(50, 50))
        self.PB_ZD2x.setCheckable(False)
        self.PB_ZD2x.setFlat(False)
        self.PB_ZD2x.setObjectName(_fromUtf8("PB_ZD2x"))
        self.PB_ZU3x = QtGui.QPushButton(Form)
        self.PB_ZU3x.setGeometry(QtCore.QRect(550, 0, 61, 71))
        self.PB_ZU3x.setMouseTracking(True)
        self.PB_ZU3x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_ZU3x.setAutoFillBackground(False)
        self.PB_ZU3x.setText(_fromUtf8(""))
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8("ZU3Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_ZU3x.setIcon(icon15)
        self.PB_ZU3x.setIconSize(QtCore.QSize(70, 70))
        self.PB_ZU3x.setCheckable(False)
        self.PB_ZU3x.setFlat(False)
        self.PB_ZU3x.setObjectName(_fromUtf8("PB_ZU3x"))
        self.PB_ZU1x = QtGui.QPushButton(Form)
        self.PB_ZU1x.setGeometry(QtCore.QRect(550, 130, 61, 51))
        self.PB_ZU1x.setMouseTracking(True)
        self.PB_ZU1x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_ZU1x.setText(_fromUtf8(""))
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8("ZU1Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_ZU1x.setIcon(icon16)
        self.PB_ZU1x.setIconSize(QtCore.QSize(50, 50))
        self.PB_ZU1x.setAutoDefault(False)
        self.PB_ZU1x.setDefault(False)
        self.PB_ZU1x.setFlat(False)
        self.PB_ZU1x.setObjectName(_fromUtf8("PB_ZU1x"))
        self.PB_ZU2x = QtGui.QPushButton(Form)
        self.PB_ZU2x.setGeometry(QtCore.QRect(550, 70, 61, 61))
        self.PB_ZU2x.setMouseTracking(True)
        self.PB_ZU2x.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.PB_ZU2x.setAutoFillBackground(False)
        self.PB_ZU2x.setText(_fromUtf8(""))
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8("ZU2Xspeed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.PB_ZU2x.setIcon(icon17)
        self.PB_ZU2x.setIconSize(QtCore.QSize(50, 50))
        self.PB_ZU2x.setCheckable(False)
        self.PB_ZU2x.setFlat(False)
        self.PB_ZU2x.setObjectName(_fromUtf8("PB_ZU2x"))
        self.XYSpeed_1x_slider = QtGui.QSlider(Form)
        self.XYSpeed_1x_slider.setGeometry(QtCore.QRect(90, 480, 171, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.XYSpeed_1x_slider.setFont(font)
        self.XYSpeed_1x_slider.setMaximum(500)
        self.XYSpeed_1x_slider.setSingleStep(50)
        self.XYSpeed_1x_slider.setProperty("value", 50)
        self.XYSpeed_1x_slider.setSliderPosition(50)
        self.XYSpeed_1x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.XYSpeed_1x_slider.setInvertedAppearance(False)
        self.XYSpeed_1x_slider.setInvertedControls(False)
        self.XYSpeed_1x_slider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.XYSpeed_1x_slider.setTickInterval(0)
        self.XYSpeed_1x_slider.setObjectName(_fromUtf8("XYSpeed_1x_slider"))
        self.pushButton_L1x_8 = QtGui.QPushButton(Form)
        self.pushButton_L1x_8.setGeometry(QtCore.QRect(40, 470, 40, 40))
        self.pushButton_L1x_8.setMouseTracking(True)
        self.pushButton_L1x_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_L1x_8.setText(_fromUtf8(""))
        self.pushButton_L1x_8.setIcon(icon5)
        self.pushButton_L1x_8.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_L1x_8.setAutoDefault(False)
        self.pushButton_L1x_8.setDefault(False)
        self.pushButton_L1x_8.setFlat(False)
        self.pushButton_L1x_8.setObjectName(_fromUtf8("pushButton_L1x_8"))
        self.pushButton_R1x_15 = QtGui.QPushButton(Form)
        self.pushButton_R1x_15.setGeometry(QtCore.QRect(40, 510, 41, 41))
        self.pushButton_R1x_15.setMouseTracking(True)
        self.pushButton_R1x_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_R1x_15.setAutoFillBackground(False)
        self.pushButton_R1x_15.setText(_fromUtf8(""))
        self.pushButton_R1x_15.setIcon(icon3)
        self.pushButton_R1x_15.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_R1x_15.setCheckable(False)
        self.pushButton_R1x_15.setFlat(False)
        self.pushButton_R1x_15.setObjectName(_fromUtf8("pushButton_R1x_15"))
        self.pushButton_R1x_16 = QtGui.QPushButton(Form)
        self.pushButton_R1x_16.setGeometry(QtCore.QRect(20, 550, 60, 40))
        self.pushButton_R1x_16.setMouseTracking(True)
        self.pushButton_R1x_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton_R1x_16.setAutoFillBackground(False)
        self.pushButton_R1x_16.setText(_fromUtf8(""))
        self.pushButton_R1x_16.setIcon(icon4)
        self.pushButton_R1x_16.setIconSize(QtCore.QSize(50, 40))
        self.pushButton_R1x_16.setCheckable(False)
        self.pushButton_R1x_16.setFlat(False)
        self.pushButton_R1x_16.setObjectName(_fromUtf8("pushButton_R1x_16"))
        self.XYSpeed_3x_value = QtGui.QDoubleSpinBox(Form)
        self.XYSpeed_3x_value.setGeometry(QtCore.QRect(270, 560, 62, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.XYSpeed_3x_value.setFont(font)
        self.XYSpeed_3x_value.setObjectName(_fromUtf8("XYSpeed_3x_value"))
        self.X_stage_value = QtGui.QLCDNumber(Form)
        self.X_stage_value.setGeometry(QtCore.QRect(50, 50, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.X_stage_value.setFont(font)
        self.X_stage_value.setDigitCount(6)
        self.X_stage_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.X_stage_value.setObjectName(_fromUtf8("X_stage_value"))
        self.Y_stage_value = QtGui.QLCDNumber(Form)
        self.Y_stage_value.setGeometry(QtCore.QRect(50, 110, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Y_stage_value.setFont(font)
        self.Y_stage_value.setDigitCount(6)
        self.Y_stage_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Y_stage_value.setObjectName(_fromUtf8("Y_stage_value"))
        self.x1_unit = QtGui.QLabel(Form)
        self.x1_unit.setGeometry(QtCore.QRect(340, 480, 51, 31))
        self.x1_unit.setObjectName(_fromUtf8("x1_unit"))
        self.x2_unit = QtGui.QLabel(Form)
        self.x2_unit.setGeometry(QtCore.QRect(340, 520, 51, 31))
        self.x2_unit.setObjectName(_fromUtf8("x2_unit"))
        self.x3_unit = QtGui.QLabel(Form)
        self.x3_unit.setGeometry(QtCore.QRect(340, 560, 51, 31))
        self.x3_unit.setObjectName(_fromUtf8("x3_unit"))
        self.XY_Stage = QtGui.QLabel(Form)
        self.XY_Stage.setGeometry(QtCore.QRect(80, 0, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.XY_Stage.setFont(font)
        self.XY_Stage.setObjectName(_fromUtf8("XY_Stage"))
        self.X_X = QtGui.QLabel(Form)
        self.X_X.setGeometry(QtCore.QRect(20, 50, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.X_X.setFont(font)
        self.X_X.setObjectName(_fromUtf8("X_X"))
        self.Y_Y = QtGui.QLabel(Form)
        self.Y_Y.setGeometry(QtCore.QRect(20, 110, 55, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Y_Y.setFont(font)
        self.Y_Y.setObjectName(_fromUtf8("Y_Y"))
        self.X_unit = QtGui.QLabel(Form)
        self.X_unit.setGeometry(QtCore.QRect(170, 50, 51, 31))
        self.X_unit.setObjectName(_fromUtf8("X_unit"))
        self.Y_unit = QtGui.QLabel(Form)
        self.Y_unit.setGeometry(QtCore.QRect(170, 110, 51, 31))
        self.Y_unit.setObjectName(_fromUtf8("Y_unit"))
        self.XYSpeed_2x_slider = QtGui.QSlider(Form)
        self.XYSpeed_2x_slider.setGeometry(QtCore.QRect(90, 520, 171, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.XYSpeed_2x_slider.setFont(font)
        self.XYSpeed_2x_slider.setProperty("value", 0)
        self.XYSpeed_2x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.XYSpeed_2x_slider.setInvertedAppearance(False)
        self.XYSpeed_2x_slider.setInvertedControls(False)
        self.XYSpeed_2x_slider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.XYSpeed_2x_slider.setTickInterval(0)
        self.XYSpeed_2x_slider.setObjectName(_fromUtf8("XYSpeed_2x_slider"))
        self.XYSpeed_3x_slider = QtGui.QSlider(Form)
        self.XYSpeed_3x_slider.setGeometry(QtCore.QRect(90, 560, 171, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.XYSpeed_3x_slider.setFont(font)
        self.XYSpeed_3x_slider.setProperty("value", 0)
        self.XYSpeed_3x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.XYSpeed_3x_slider.setInvertedAppearance(False)
        self.XYSpeed_3x_slider.setInvertedControls(False)
        self.XYSpeed_3x_slider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.XYSpeed_3x_slider.setTickInterval(0)
        self.XYSpeed_3x_slider.setObjectName(_fromUtf8("XYSpeed_3x_slider"))
        self.ZSpeed_3x_value = QtGui.QDoubleSpinBox(Form)
        self.ZSpeed_3x_value.setGeometry(QtCore.QRect(630, 560, 62, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ZSpeed_3x_value.setFont(font)
        self.ZSpeed_3x_value.setObjectName(_fromUtf8("ZSpeed_3x_value"))
        self.zx1_unit = QtGui.QLabel(Form)
        self.zx1_unit.setGeometry(QtCore.QRect(700, 470, 51, 31))
        self.zx1_unit.setObjectName(_fromUtf8("zx1_unit"))
        self.zx3_unit = QtGui.QLabel(Form)
        self.zx3_unit.setGeometry(QtCore.QRect(700, 560, 51, 31))
        self.zx3_unit.setObjectName(_fromUtf8("zx3_unit"))
        self.ZSpeed_2x_slider = QtGui.QSlider(Form)
        self.ZSpeed_2x_slider.setGeometry(QtCore.QRect(450, 520, 171, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ZSpeed_2x_slider.setFont(font)
        self.ZSpeed_2x_slider.setProperty("value", 0)
        self.ZSpeed_2x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ZSpeed_2x_slider.setInvertedAppearance(False)
        self.ZSpeed_2x_slider.setInvertedControls(False)
        self.ZSpeed_2x_slider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.ZSpeed_2x_slider.setTickInterval(0)
        self.ZSpeed_2x_slider.setObjectName(_fromUtf8("ZSpeed_2x_slider"))
        self.zx2_unit = QtGui.QLabel(Form)
        self.zx2_unit.setGeometry(QtCore.QRect(700, 520, 51, 31))
        self.zx2_unit.setObjectName(_fromUtf8("zx2_unit"))
        self.ZSpeed_1x_slider = QtGui.QSlider(Form)
        self.ZSpeed_1x_slider.setGeometry(QtCore.QRect(450, 480, 171, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ZSpeed_1x_slider.setFont(font)
        self.ZSpeed_1x_slider.setProperty("value", 0)
        self.ZSpeed_1x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ZSpeed_1x_slider.setInvertedAppearance(False)
        self.ZSpeed_1x_slider.setInvertedControls(False)
        self.ZSpeed_1x_slider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.ZSpeed_1x_slider.setTickInterval(0)
        self.ZSpeed_1x_slider.setObjectName(_fromUtf8("ZSpeed_1x_slider"))
        self.ZSpeed_3x_slider = QtGui.QSlider(Form)
        self.ZSpeed_3x_slider.setGeometry(QtCore.QRect(450, 560, 171, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ZSpeed_3x_slider.setFont(font)
        self.ZSpeed_3x_slider.setProperty("value", 0)
        self.ZSpeed_3x_slider.setOrientation(QtCore.Qt.Horizontal)
        self.ZSpeed_3x_slider.setInvertedAppearance(False)
        self.ZSpeed_3x_slider.setInvertedControls(False)
        self.ZSpeed_3x_slider.setTickPosition(QtGui.QSlider.TicksBothSides)
        self.ZSpeed_3x_slider.setTickInterval(0)
        self.ZSpeed_3x_slider.setObjectName(_fromUtf8("ZSpeed_3x_slider"))
        self.Z_unit = QtGui.QLabel(Form)
        self.Z_unit.setGeometry(QtCore.QRect(670, 200, 51, 31))
        self.Z_unit.setObjectName(_fromUtf8("Z_unit"))
        self.Z_stage_value = QtGui.QLCDNumber(Form)
        self.Z_stage_value.setGeometry(QtCore.QRect(550, 200, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.Z_stage_value.setFont(font)
        self.Z_stage_value.setDigitCount(6)
        self.Z_stage_value.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.Z_stage_value.setObjectName(_fromUtf8("Z_stage_value"))
        self.Z_Stage = QtGui.QLabel(Form)
        self.Z_Stage.setGeometry(QtCore.QRect(630, 0, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Z_Stage.setFont(font)
        self.Z_Stage.setObjectName(_fromUtf8("Z_Stage"))
        self.XYSpeed_1x_value = QtGui.QSpinBox(Form)
        self.XYSpeed_1x_value.setGeometry(QtCore.QRect(270, 480, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.XYSpeed_1x_value.setFont(font)
        self.XYSpeed_1x_value.setMaximum(500)
        self.XYSpeed_1x_value.setObjectName(_fromUtf8("XYSpeed_1x_value"))
        self.XYSpeed_2x_value = QtGui.QSpinBox(Form)
        self.XYSpeed_2x_value.setGeometry(QtCore.QRect(270, 520, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.XYSpeed_2x_value.setFont(font)
        self.XYSpeed_2x_value.setMaximum(500)
        self.XYSpeed_2x_value.setObjectName(_fromUtf8("XYSpeed_2x_value"))
        self.ZSpeed_1x_value = QtGui.QSpinBox(Form)
        self.ZSpeed_1x_value.setGeometry(QtCore.QRect(630, 480, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ZSpeed_1x_value.setFont(font)
        self.ZSpeed_1x_value.setMaximum(500)
        self.ZSpeed_1x_value.setObjectName(_fromUtf8("ZSpeed_1x_value"))
        self.ZSpeed_2x_value = QtGui.QSpinBox(Form)
        self.ZSpeed_2x_value.setGeometry(QtCore.QRect(630, 520, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ZSpeed_2x_value.setFont(font)
        self.ZSpeed_2x_value.setMaximum(500)
        self.ZSpeed_2x_value.setObjectName(_fromUtf8("ZSpeed_2x_value"))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.x1_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">nm</span></p></body></html>", None))
        self.x2_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">nm</span></p></body></html>", None))
        self.x3_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">um</span></p></body></html>", None))
        self.XY_Stage.setText(_translate("Form", "XY Stage", None))
        self.X_X.setText(_translate("Form", "X", None))
        self.Y_Y.setText(_translate("Form", "Y", None))
        self.X_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">um</span></p></body></html>", None))
        self.Y_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">um</span></p></body></html>", None))
        self.zx1_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">nm</span></p></body></html>", None))
        self.zx3_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">um</span></p></body></html>", None))
        self.zx2_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">nm</span></p></body></html>", None))
        self.Z_unit.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">um</span></p></body></html>", None))
        self.Z_Stage.setText(_translate("Form", "Z Stage", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

