%YAML 1.2
---
# Default parameters for the Tracking program
# All parameters can be changed to accommodate user needs.
# All parameters can be changed at runtime with the appropriate config window
User:
  name: Zhu
  measurement: Sample

Saving:
  autosave_raw_images: False
  autosave_trajectory: False
  directory: C:\data
  filename_video: Video # Can be the same filename for video and photo
  filename_photo: Snap
  filename_waterfall: Waterfall
  filename_trajectory: Trajectory
  filename_log: Log
  max_memory: 15000 # In megabytes

GUI:
  length_waterfall: 100 # # Number of Waterfall lines collected before saving and refreshing
  vbin_waterfall: 20 # Number of pixels summed up at the vertical center of the captured frame for waterfall
  refresh_time: 50 # Refresh rate of the GUI (in ms)

Camera:
  camera: photometrics  # the camera to use
  model: PM  #OrcaFlash4  #Basler puA1600
  ADCSpeed: 100MHz
  ADCGain: HDR
  Cooling: 0 #Cooling method high speed fan
  exposure_mode: Internal Trigger #  supported: 'Internal Trigger': 1792, 'Edge Trigger': 2304, 'Trigger first': 2048
  exposure_time: 1 # Initial exposure time
  exposure_unit: ms # Initial exposure time unit
#  FPS_limit: 200 # 200 is the normal value NOT IMPLEMENTED
  binning_x: 1
  binning_y: 1
  roi_x1: 0 # Leave at 0 for full camera
  roi_x2: 100
  roi_y1: 0
  roi_y2: 100
  future_background_method: '' #Method1
  contrast_phase: 0 # Change phase of contrast mode

SquareWaveFPSCtrl:
  frequency: 10. # Hz
  4CameraFPS: Egde trigger! 


Potentiostat:
  Tech: CV # CV, CA, or SSF
  ExtTri: True # 0=False, 1=True
  kick_cam: True # 0=False, 1=True

CV:
  Eini: 0.0 # V, initial potential
  Ev1: 0.0  # V, first vertex potential
  Ev2: -0.5  #  V, second vertex potential
  Efin: 0.0 # V, finad potential
  SR: 0.5  # V/s, scan rate
  dE: 0.001  #  V, potential increment
  nSweeps: 2 # number of sweeps
  sens: 1e-5  # A/V, current sensitivity
 

SSF:
  Eini: 0.0 # initial potential in V
  Eholding: -1.1 # potential to be hodling
  holdingTime: 20 # holding time
  Eend: 0.0  # end potential
  SR: 0.02 # scan rate
  dE: 0.001 # sweep sample interval in V
  sens: 1e-5 # A/V, current sensitivity
  dt: 0.01 # step sample interval in s
  qt: 2 # quiescent time before run in s

Wavegeneration:
  frequency: 10.  # Hz
  amplitude: 0.5  # V
  time_per_offset: 5  # seconds
  cycles: 1  # number of cycles
  offset_start: -0.5  # V
  offset_end: 0.5  # V
  offset_step: 0.5  # V per step
  auto_measure: 0  # 0=False, 1=True

Tracking: # implementation in progress, expect errors
  particle_size: 8 # expected particle size (FWHM) in pixels, set to zero for automatic estimation
  step_size: 2 # expected particle jump between frames for adjusting the search area
  noise_level: 9 # dark counts plus noise level, all values below will be set to zero for tracking an object
  future_view_track: X-Y # choosing the desired track to view x-intensity, or x-y coordinates
  future_localization_method: CenMass # chosen localization method
  future_snr: 0 # expected signal to noise ratio, set to zero for automatic estimation

Debug:
  queue_memory: False
  to_screen: False
